# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(10, 10, 661, 351))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("img/docker.png"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.github = QtWidgets.QPushButton(self.centralwidget)
        self.github.setGeometry(QtCore.QRect(530, 400, 111, 41))
        self.github.setObjectName("github")
        self.vscode = QtWidgets.QPushButton(self.centralwidget)
        self.vscode.setGeometry(QtCore.QRect(450, 460, 111, 41))
        self.vscode.setObjectName("vscode")
        self.python = QtWidgets.QPushButton(self.centralwidget)
        self.python.setGeometry(QtCore.QRect(280, 460, 111, 41))
        self.python.setObjectName("python")
        self.opencv = QtWidgets.QPushButton(self.centralwidget)
        self.opencv.setGeometry(QtCore.QRect(110, 460, 111, 41))
        self.opencv.setObjectName("opencv")
        self.docker = QtWidgets.QPushButton(self.centralwidget)
        self.docker.setGeometry(QtCore.QRect(40, 400, 111, 41))
        self.docker.setObjectName("docker")
        self.flask = QtWidgets.QPushButton(self.centralwidget)
        self.flask.setGeometry(QtCore.QRect(200, 400, 111, 41))
        self.flask.setObjectName("flask")
        self.git = QtWidgets.QPushButton(self.centralwidget)
        self.git.setGeometry(QtCore.QRect(370, 400, 111, 41))
        self.git.setObjectName("git")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.docker.clicked.connect(self.show_docker)
        self.flask.clicked.connect(self.show_flask)
        self.git.clicked.connect(self.show_git)
        self.github.clicked.connect(self.show_github)
        self.opencv.clicked.connect(self.show_opencv)
        self.python.clicked.connect(self.show_python)
        self.vscode.clicked.connect(self.show_vscode)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.github.setText(_translate("MainWindow", "GitHub"))
        self.vscode.setText(_translate("MainWindow", "VSCode"))
        self.python.setText(_translate("MainWindow", "Python"))
        self.opencv.setText(_translate("MainWindow", "OpenCV"))
        self.docker.setText(_translate("MainWindow", "Docker"))
        self.flask.setText(_translate("MainWindow", "Flask"))
        self.git.setText(_translate("MainWindow", "Git"))
    
    def show_docker(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/docker.png"))
    def show_flask(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/flask.png"))
    def show_git(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/git.png"))
    def show_github(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/github.png"))
    def show_opencv(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/opencv.png"))
    def show_python(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/python.png"))
    def show_vscode(self):
        self.Photo.setPixmap(QtGui.QPixmap("img/vscode.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
