# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PopupTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.critical = QtWidgets.QPushButton(self.centralwidget)
        self.critical.setGeometry(QtCore.QRect(50, 40, 121, 61))
        self.critical.setObjectName("critical")
        self.warning = QtWidgets.QPushButton(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(340, 40, 131, 61))
        self.warning.setObjectName("warning")
        self.information = QtWidgets.QPushButton(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(50, 180, 121, 61))
        self.information.setObjectName("information")
        self.question = QtWidgets.QPushButton(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(340, 180, 131, 61))
        self.question.setObjectName("question")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.critical.clicked.connect(self.show_popup_critical)
        self.warning.clicked.connect(self.show_popup_warning)
        self.information.clicked.connect(self.show_popup_information)
        self.question.clicked.connect(self.show_popup_question)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.critical.setText(_translate("MainWindow", "Critical"))
        self.warning.setText(_translate("MainWindow", "Warning"))
        self.information.setText(_translate("MainWindow", "Information"))
        self.question.setText(_translate("MainWindow", "Question"))

    def show_popup_critical(self):
        msg = QMessageBox()
        msg.setWindowTitle("Alert")
        msg.setText("This is a critical alert !!!!!")
        msg.setIcon(QMessageBox.Critical)
        msg.setStandardButtons(QMessageBox.Cancel | QMessageBox.Retry | QMessageBox.Ignore)
        msg.setDefaultButton(QMessageBox.Cancel)
        msg.setInformativeText("This is the informative text!")
        msg.setDetailedText("This is the detailed Text!!!!!!!!!!!!!!!!!!!!!")

        msg.buttonClicked.connect(self.popup_button)

        x = msg.exec_()
    
    def show_popup_warning(self):
        msg = QMessageBox()
        msg.setWindowTitle("Alert")
        msg.setText("This is a warning alert !!!!!")
        msg.setIcon(QMessageBox.Warning)
        msg.setStandardButtons(QMessageBox.Abort | QMessageBox.Cancel | QMessageBox.Ignore)
        msg.setDefaultButton(QMessageBox.Abort)
        msg.setInformativeText("This is the informative text!")
        msg.setDetailedText("This is the detailed Text!!!!!!!!!!!!!!!!!!!!!")

        msg.buttonClicked.connect(self.popup_button)

        x = msg.exec_()

    def show_popup_information(self):
        msg = QMessageBox()
        msg.setWindowTitle("Alert")
        msg.setText("This is an information alert !!!!!")
        msg.setIcon(QMessageBox.Information)
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No | QMessageBox.Save)
        msg.setDefaultButton(QMessageBox.Yes)
        msg.setInformativeText("This is the informative text!")
        msg.setDetailedText("This is the detailed Text!!!!!!!!!!!!!!!!!!!!!")

        msg.buttonClicked.connect(self.popup_button)

        x = msg.exec_()

    def show_popup_question(self):
        msg = QMessageBox()
        msg.setWindowTitle("Alert")
        msg.setText("This is a question alert !!!!!")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Open | QMessageBox.Close)
        msg.setDefaultButton(QMessageBox.Open)
        msg.setInformativeText("This is the informative text!")
        msg.setDetailedText("This is the detailed Text!!!!!!!!!!!!!!!!!!!!!")

        msg.buttonClicked.connect(self.popup_button)

        x = msg.exec_()

    def popup_button(self, i):
        print(i.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
