# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpinBoxTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(140, 80, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.TheY = QtWidgets.QSpinBox(self.centralwidget)
        self.TheY.setGeometry(QtCore.QRect(370, 80, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.TheY.setFont(font)
        self.TheY.setObjectName("TheY")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 140, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(50, 210, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(50, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(430, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(430, 210, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add.clicked.connect(self.adding)
        self.minus.clicked.connect(self.minusing)
        self.multiply.clicked.connect(self.multiple)
        self.divide.clicked.connect(self.divided)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "The result: "))
        self.add.setText(_translate("MainWindow", "+"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.minus.setText(_translate("MainWindow", "-"))

    def adding(self):
        r = self.spinBox.value() + self.TheY.value()
        self.label.setText("The result: " + str(r))
    def minusing(self):
        r = self.spinBox.value() - self.TheY.value()
        self.label.setText("The result: " + str(r))
    def multiple(self):
        r = self.spinBox.value() * self.TheY.value()
        self.label.setText("The result: " + str(r))
    def divided(self):
        r = self.spinBox.value() // self.TheY.value()
        self.label.setText("The result: " + str(r))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
